resolver: lts-8.5
packages:
- '.'
- location:
    git: https://github.com/saltlang/dynamic-pprint.git
    commit: 58dffdba55b76d2f1d9c9d2e661afd8e3fc28fdb
- location:
    git: http://github.com/saltlang/compiler-toolbox.git
    commit: f8a799393adaff7184acbd7a8609b80e74420c56
extra-deps: [ HUnit-Plus-2.0.0, hexpat-pickle-0.6, bitwise-0.1.1.1,
              ]
flags: {}
extra-package-dbs: []

